package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_catelog;

public interface T_catelogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_catelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_catelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_catelog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_catelog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_catelog
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_catelog record);

	List<T_catelog> selectByAll();


	List<T_catelog> selectByinfo(String catelogname);
}