package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_eamil;

public interface T_eamilMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_eamil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_eamil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_eamil selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_eamil record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eamil
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_eamil record);

	List<T_eamil> selectByPrimaryKeytolist();
}