package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_food;

public interface T_foodMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	int insert(T_food record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	int insertSelective(T_food record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	T_food selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	int updateByPrimaryKeySelective(T_food record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_food
	 *
	 * @mbggenerated Mon Jul 17 11:41:22 CST 2017
	 */
	int updateByPrimaryKey(T_food record);

	List<T_food> selectByAll();

	List<T_food> getUserByName(String id);

	T_food getOneByName(String id);

	List<T_food> selectByName(String foodname);
	//共有几页的分页查询
	List<T_food> getYeShuByName(String id);
	//下一页
	List<T_food> getFenByName(String id, int begin, int end);
}