package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_message;

public interface T_messageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_message selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_message
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_message record);

	List<T_message> selectByAll();
}