package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_notice;

public interface T_noticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_notice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_notice record);

	List<T_notice> selectByAll();
}