package com.Indent.dao;

import java.util.List;

import com.Indent.vo.T_order;

public interface T_orderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_order selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_order record);

	List<T_order> selectByAll();//更改成id查询s

	List<T_order> selectmyorder(String id);
	//购物车付钱按钮事件功能
	int Gouwuche(String uuid, String z_id, int i, String d, String user_id);

	T_order hui_gouwu(String user_id);
}