package com.Indent.dao;

import com.Indent.vo.T_orderm;

public interface T_ordermMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_orderm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_orderm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_orderm selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_orderm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_orderm
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_orderm record);
}