package com.Indent.dao;

import java.util.List;

import org.apache.catalina.User;
import org.springframework.stereotype.Component;

import com.Indent.vo.T_admin;
import com.Indent.vo.T_user;
@Component
public interface T_userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insert(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int insertSelective(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    T_user selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKeySelective(T_user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    int updateByPrimaryKey(T_user record);

	int regist(T_user user);

	T_user selectUsername(String username);

	T_user selectTel(String tel);

	T_user login(T_user user);
	int usserregist(T_user user);

	T_user userlogin(T_user user);

	void updatelogintime(T_user user);

	boolean updatepassword(String tel, String oldpassword, String newpassword);

	T_user testpassword(String id, String password);

	T_user true_updatepassword(String tel, String newpassword);

	T_user false_updatepassword(String tel, String oldpassword);

	Boolean updateuser(T_user t_user);

	T_user true_updateuser(T_user t_user);

	List<T_user> selectAll();


	T_user testusername(String username);

	T_user testtel(String tel);

	List<T_user> selectByName(String realname);

	void updatetime(T_user t_user);


}