package com.Indent.vo;

public class T_catelog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catelog.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catelog.catelog_info
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String catelogInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_catelog.catelog_name
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String catelogName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catelog.id
     *
     * @return the value of t_catelog.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catelog.id
     *
     * @param id the value for t_catelog.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catelog.catelog_info
     *
     * @return the value of t_catelog.catelog_info
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getCatelogInfo() {
        return catelogInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catelog.catelog_info
     *
     * @param catelogInfo the value for t_catelog.catelog_info
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setCatelogInfo(String catelogInfo) {
        this.catelogInfo = catelogInfo == null ? null : catelogInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_catelog.catelog_name
     *
     * @return the value of t_catelog.catelog_name
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getCatelogName() {
        return catelogName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_catelog.catelog_name
     *
     * @param catelogName the value for t_catelog.catelog_name
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setCatelogName(String catelogName) {
        this.catelogName = catelogName == null ? null : catelogName.trim();
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((catelogInfo == null) ? 0 : catelogInfo.hashCode());
		result = prime * result + ((catelogName == null) ? 0 : catelogName.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		T_catelog other = (T_catelog) obj;
		if (catelogInfo == null) {
			if (other.catelogInfo != null)
				return false;
		} else if (!catelogInfo.equals(other.catelogInfo))
			return false;
		if (catelogName == null) {
			if (other.catelogName != null)
				return false;
		} else if (!catelogName.equals(other.catelogName))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "T_catelog [id=" + id + ", catelogInfo=" + catelogInfo + ", catelogName=" + catelogName + "]";
	}

	public T_catelog(String id, String catelogInfo, String catelogName) {
		this.id = id;
		this.catelogInfo = catelogInfo;
		this.catelogName = catelogName;
	}

	public T_catelog() {
	}
    
}