package com.Indent.vo;

import java.util.List;

import org.springframework.stereotype.Component;

import sun.print.resources.serviceui;

@Component
public class T_food {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String id;
    private String tel;

    public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public T_food(String id, String foodinfo, String foodname, String photo, Double price) {
		super();
		this.id = id;
		this.foodinfo = foodinfo;
		this.foodname = foodname;
		this.photo = photo;
		this.price = price;
	}

	public T_food() {
		super();
	}

	public T_food(String id, String foodinfo, String foodname, String photo, Double price, String catelogId,
			Integer num ,String tel) {
		this.id = id;
		this.foodinfo = foodinfo;
		this.foodname = foodname;
		this.photo = photo;
		this.price = price;
		this.catelogId = catelogId;
		this.num = num;
		this.tel = tel;
	}

	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((catelogId == null) ? 0 : catelogId.hashCode());
		result = prime * result + ((foodinfo == null) ? 0 : foodinfo.hashCode());
		result = prime * result + ((foodname == null) ? 0 : foodname.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((num == null) ? 0 : num.hashCode());
		result = prime * result + ((photo == null) ? 0 : photo.hashCode());
		result = prime * result + ((price == null) ? 0 : price.hashCode());
		result = prime * result + ((tel == null) ? 0 : tel.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		T_food other = (T_food) obj;
		if (catelogId == null) {
			if (other.catelogId != null)
				return false;
		} else if (!catelogId.equals(other.catelogId))
			return false;
		if (foodinfo == null) {
			if (other.foodinfo != null)
				return false;
		} else if (!foodinfo.equals(other.foodinfo))
			return false;
		if (foodname == null) {
			if (other.foodname != null)
				return false;
		} else if (!foodname.equals(other.foodname))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (num == null) {
			if (other.num != null)
				return false;
		} else if (!num.equals(other.num))
			return false;
		if (photo == null) {
			if (other.photo != null)
				return false;
		} else if (!photo.equals(other.photo))
			return false;
		if (price == null) {
			if (other.price != null)
				return false;
		} else if (!price.equals(other.price))
			return false;
		if (tel == null) {
			if (other.tel != null)
				return false;
		} else if (!tel.equals(other.tel))
			return false;
		return true;
	}



	@Override
	public String toString() {
		return "T_food [id=" + id + ", tel=" + tel + ", foodinfo=" + foodinfo + ", foodname=" + foodname + ", photo="
				+ photo + ", price=" + price + ", catelogId=" + catelogId + ", num=" + num + "]";
	}



	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.foodinfo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String foodinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.foodname
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.photo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.price
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.catelog_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String catelogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_food.num
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private Integer num;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.id
     *
     * @return the value of t_food.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.id
     *
     * @param id the value for t_food.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.foodinfo
     *
     * @return the value of t_food.foodinfo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getFoodinfo() {
        return foodinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.foodinfo
     *
     * @param foodinfo the value for t_food.foodinfo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setFoodinfo(String foodinfo) {
        this.foodinfo = foodinfo == null ? null : foodinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.foodname
     *
     * @return the value of t_food.foodname
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.foodname
     *
     * @param foodname the value for t_food.foodname
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.photo
     *
     * @return the value of t_food.photo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.photo
     *
     * @param photo the value for t_food.photo
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

 

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.price
     *
     * @return the value of t_food.price
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.price
     *
     * @param price the value for t_food.price
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.catelog_id
     *
     * @return the value of t_food.catelog_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getCatelogId() {
        return catelogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.catelog_id
     *
     * @param catelogId the value for t_food.catelog_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setCatelogId(String catelogId) {
        this.catelogId = catelogId == null ? null : catelogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_food.num
     *
     * @return the value of t_food.num
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_food.num
     *
     * @param num the value for t_food.num
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setNum(Integer num) {
        this.num = num;
    }


}