package com.Indent.vo;

import java.util.Date;

public class T_notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.content
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.create_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.title
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.update_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.admin_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.id
     *
     * @return the value of t_notice.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.id
     *
     * @param id the value for t_notice.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.content
     *
     * @return the value of t_notice.content
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.content
     *
     * @param content the value for t_notice.content
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.create_time
     *
     * @return the value of t_notice.create_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.create_time
     *
     * @param createTime the value for t_notice.create_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.title
     *
     * @return the value of t_notice.title
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.title
     *
     * @param title the value for t_notice.title
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.update_time
     *
     * @return the value of t_notice.update_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.update_time
     *
     * @param updateTime the value for t_notice.update_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.admin_id
     *
     * @return the value of t_notice.admin_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.admin_id
     *
     * @param adminId the value for t_notice.admin_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((adminId == null) ? 0 : adminId.hashCode());
		result = prime * result + ((content == null) ? 0 : content.hashCode());
		result = prime * result + ((createTime == null) ? 0 : createTime.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		result = prime * result + ((updateTime == null) ? 0 : updateTime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		T_notice other = (T_notice) obj;
		if (adminId == null) {
			if (other.adminId != null)
				return false;
		} else if (!adminId.equals(other.adminId))
			return false;
		if (content == null) {
			if (other.content != null)
				return false;
		} else if (!content.equals(other.content))
			return false;
		if (createTime == null) {
			if (other.createTime != null)
				return false;
		} else if (!createTime.equals(other.createTime))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		if (updateTime == null) {
			if (other.updateTime != null)
				return false;
		} else if (!updateTime.equals(other.updateTime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "T_notice [id=" + id + ", content=" + content + ", createTime=" + createTime + ", title=" + title
				+ ", updateTime=" + updateTime + ", adminId=" + adminId + "]";
	}

	public T_notice(String id, String content, Date createTime, String title, Date updateTime, String adminId) {
		super();
		this.id = id;
		this.content = content;
		this.createTime = createTime;
		this.title = title;
		this.updateTime = updateTime;
		this.adminId = adminId;
	}

	public T_notice() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}