package com.Indent.vo;

import java.util.Date;

public class T_orderm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderm.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderm.order_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private Date orderTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderm.food_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String foodId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_orderm.order_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderm.id
     *
     * @return the value of t_orderm.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderm.id
     *
     * @param id the value for t_orderm.id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderm.order_time
     *
     * @return the value of t_orderm.order_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderm.order_time
     *
     * @param orderTime the value for t_orderm.order_time
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderm.food_id
     *
     * @return the value of t_orderm.food_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getFoodId() {
        return foodId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderm.food_id
     *
     * @param foodId the value for t_orderm.food_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setFoodId(String foodId) {
        this.foodId = foodId == null ? null : foodId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_orderm.order_id
     *
     * @return the value of t_orderm.order_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_orderm.order_id
     *
     * @param orderId the value for t_orderm.order_id
     *
     * @mbggenerated Mon Jul 17 11:41:22 CST 2017
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((foodId == null) ? 0 : foodId.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		result = prime * result + ((orderTime == null) ? 0 : orderTime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		T_orderm other = (T_orderm) obj;
		if (foodId == null) {
			if (other.foodId != null)
				return false;
		} else if (!foodId.equals(other.foodId))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		if (orderTime == null) {
			if (other.orderTime != null)
				return false;
		} else if (!orderTime.equals(other.orderTime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "T_orderm [id=" + id + ", orderTime=" + orderTime + ", foodId=" + foodId + ", orderId=" + orderId + "]";
	}

	public T_orderm(String id, Date orderTime, String foodId, String orderId) {
		super();
		this.id = id;
		this.orderTime = orderTime;
		this.foodId = foodId;
		this.orderId = orderId;
	}

	public T_orderm() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}