package com.Indent.vo;

public class T_shopp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.foodinfo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String foodinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.foodname
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String foodname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.photo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.price
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.tel
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopp.order_id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    private String orderId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.id
     *
     * @return the value of t_shopp.id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.id
     *
     * @param id the value for t_shopp.id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.foodinfo
     *
     * @return the value of t_shopp.foodinfo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getFoodinfo() {
        return foodinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.foodinfo
     *
     * @param foodinfo the value for t_shopp.foodinfo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setFoodinfo(String foodinfo) {
        this.foodinfo = foodinfo == null ? null : foodinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.foodname
     *
     * @return the value of t_shopp.foodname
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getFoodname() {
        return foodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.foodname
     *
     * @param foodname the value for t_shopp.foodname
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setFoodname(String foodname) {
        this.foodname = foodname == null ? null : foodname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.photo
     *
     * @return the value of t_shopp.photo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.photo
     *
     * @param photo the value for t_shopp.photo
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.price
     *
     * @return the value of t_shopp.price
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.price
     *
     * @param price the value for t_shopp.price
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.tel
     *
     * @return the value of t_shopp.tel
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.tel
     *
     * @param tel the value for t_shopp.tel
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopp.order_id
     *
     * @return the value of t_shopp.order_id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopp.order_id
     *
     * @param orderId the value for t_shopp.order_id
     *
     * @mbggenerated Wed Jul 26 20:37:01 CST 2017
     */
//    public void setOrderId(String orderId) {
//        this.orderId = orderId == null ? null : orderId.trim();
//    }

	@Override
	public String toString() {
		return "T_shopp [id=" + id + ", foodinfo=" + foodinfo + ", foodname=" + foodname + ", photo=" + photo
				+ ", price=" + price + ", tel=" + tel + ", orderId=" + orderId + "]";
	}

	public T_shopp() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((foodinfo == null) ? 0 : foodinfo.hashCode());
		result = prime * result + ((foodname == null) ? 0 : foodname.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		result = prime * result + ((photo == null) ? 0 : photo.hashCode());
		result = prime * result + ((price == null) ? 0 : price.hashCode());
		result = prime * result + ((tel == null) ? 0 : tel.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		T_shopp other = (T_shopp) obj;
		if (foodinfo == null) {
			if (other.foodinfo != null)
				return false;
		} else if (!foodinfo.equals(other.foodinfo))
			return false;
		if (foodname == null) {
			if (other.foodname != null)
				return false;
		} else if (!foodname.equals(other.foodname))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		if (photo == null) {
			if (other.photo != null)
				return false;
		} else if (!photo.equals(other.photo))
			return false;
		if (price == null) {
			if (other.price != null)
				return false;
		} else if (!price.equals(other.price))
			return false;
		if (tel == null) {
			if (other.tel != null)
				return false;
		} else if (!tel.equals(other.tel))
			return false;
		return true;
	}

	public T_shopp(String id, String foodinfo, String foodname, String photo, Double price, String tel,
			String orderId) {
		super();
		this.id = id;
		this.foodinfo = foodinfo;
		this.foodname = foodname;
		this.photo = photo;
		this.price = price;
		this.tel = tel;
		this.orderId = orderId;
	}
    
}